# Site settings
title: ab180
logo: "img/img_ab180_transparent_white.png"
footer-img: "img/img_ab180_footer_777.png"
header-img: img/home-bg.png
email: dl_all@udl.io
description: "ab180의 회사 공식 홈페이지"
baseurl: ""
url: "legacy.ab180.co"
twitter_username:
github_username: teamab180
facebook_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
